---
# Defaults for check-system role
# ALL values must be defined in group_vars/all.yml
# This file is kept for variable structure documentation

# Variables used by this role:
# - system_requirements (dictionary with system requirements)
#   - min_memory_gb
#   - min_disk_gb
#   - min_kernel_version
#   - required_debian_version
#
# IMPORTANT: All values must be defined in group_vars/all.yml
# This file does not contain default values to ensure
# usage of variables from group_vars/all.yml
